---
- name: EOS Update ACL
  hosts: switches
  gather_facts: false

  tasks:
    - name: Delete test ACL
      eos_acls:
        config:
        - afi: ipv4
          acls:
          - name: test
        state: deleted
      register: result

    - name: Load an acl into the device
      arista.eos.eos_config:
        lines:
        - 10 permit ip host 192.0.2.1 any log
        - 20 permit ip host 192.0.2.2 any log
        - 30 permit ip host 192.0.2.3 any log
        - 40 permit ip host 192.0.2.4 any log
        - 50 permit ip host 192.0.2.5 any log
        parents: ip access-list test
        before: no ip access-list test


    - name: Add access-group to interface eth7
      arista.eos.eos_config:
        lines:
        - ip access-group test out
        parents: interface ethernet7
